### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by CodingCarlos** [CampusMadridProjects/directory-frontend#2]
I'm following the default style guide for vue cli generated projects, but I'm open to anything. Maybe we want to follow the same criteria here and [in the backend repo](https://github.com/CampusMadridProjects/directory-backend/) (there is also [an issue for that](https://github.com/CampusMadridProjects/directory-backend/issues/2) in that repo)

**Comment by carlosazaustre** [comment]
What code style you choose it? Aribnb or StandardJS? I'm fine with both

**Comment by CodingCarlos** [comment]
Allright! Let's go with airbnb. I love semicolons :laughing:
