### ISSUE TITLE
Translate no results to english

### ISSUE THREAD

**Issue by CodingCarlos** [CampusMadridProjects/directory-frontend#21]
The "no results" message, is in spanish. Translate to english. Might be a great point to add the link to the form for adding people. Copy might be something like: 
```
Don't find what you was looking for? Add it here!
```

**Comment by ivoriginal** [comment]
resolved: https://github.com/CampusMadridProjects/directory-frontend/tree/translated-search-results-empty

**Comment by CodingCarlos** [comment]
Cool ^^ Aproved, and ready to master!
