### ISSUE TITLE
Geo-location allows for out-of-radius access to the directory

### ISSUE THREAD

**Issue by musikame** [CampusMadridProjects/directory-frontend#31]
I can access to the directory from Torre Picasso area/further than 100m around Campus

**Comment by ivoriginal** [comment]
It's not a bug, it's a feature.

**Comment by CodingCarlos** [comment]
This is caused for a missconfiguration in the backend, done by us, becouse of the random Malaga travels of the Campus IP :airplane: 

Closing this issue, to avoid confussion ;)
