### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by CodingCarlos** [CampusMadridProjects/directory-frontend#4]
Add Google Analytics and set events to track. Is there something ready to plug-and-play in vue? 

Research needed ^^

**Comment by carlosazaustre** [comment]
I used some similar in AngularJS time ago. I could help in that part :)
To track views, clicks, etc...

**Comment by CodingCarlos** [comment]
Check if we shall or not uncheck the user tracking in analytics.

**Comment by musikame** [comment]
User tracking/ID is currently off by default

**Comment by CodingCarlos** [comment]
As we're advancing so fast, and mr Aza is on his free time, I'm starting with this issue.

In the technical part, I'm going with [vue-analytics](https://www.npmjs.com/package/vue-analytics) package, that seems to be very strong, and with [a lot of documentation](https://matteogabriele.gitbooks.io/vue-analytics/) and community.

In a more "theoircal" way, I'll be tracking page views (directly as the router does), and also events. To keep the events well organized, I've done a speadsheet with the events to track, the properties in analytics, the reasons to track it and the current status:
https://docs.google.com/spreadsheets/d/1eDe6EK6a1pOnB22vRTmYKeBo8n_qVmaIvnRbLXrE464/edit?usp=sharing

If there's something I'm missing, feel free to comment it here, or add it to the sheet _(I think all colaborators have permissions to do it)_
