### ISSUE TITLE
Review & fix slack deeplink

### ISSUE THREAD

**Issue by musikame** [CampusMadridProjects/directory-frontend#62]
Include a modal window to ask user to open slack conversation in web or app. Current button links to app URL "slack://" with issues for users without installed app

**Comment by musikame** [comment]
Update/additional details:
The issue also occurs in Slack web client (in search results after /dir-search).

FYI this script works smoothly on both desktop, mobile browser, and app (example with Carlos profile):
window.location = 'slack://user?team=TCT04PU9E&id=UFVGNPTA8';
setTimeout("window.location = 'https://app.slack.com/client/TCT04PU9E/DG36V2E2J/user_profile/UG20F12GM';", 1000);

The challenge is about getting the right IDs to create the right URLs for web & app

**Comment by musikame** [comment]
@CodingCarlos Update: I've just found that Slack is already managing this automatically with this scheme (so it redirects to app or web depending if you have it installed or not):
https://gfs-madrid.slack.com/team/[USER_ID]

Link to Ivo Profile (includes button for direct message):
https://gfs-madrid.slack.com/team/UGH2A00SX

Link to Carlos Profile:
https://gfs-madrid.slack.com/team/UFVGNPTA8

Link to Edu Profile:
https://gfs-madrid.slack.com/team/UG20F12GM

Can we please update the Slack DM link to this scheme in both Directory web and bot please?

**Comment by CodingCarlos** [comment]
Actually, it works with the apps, but not with the slack web client (redirects to the slack team, but not to the person profile). 

Anyway, I will use this for now, which is way better than what we have ;)

Thx!!

**Comment by musikame** [comment]
Good point, it open the channel in web + the user profile panel in the
right side, doesn't it?
Thx for checking!

On the go, please excuse brevity & typ0$

**Comment by musikame** [comment]
@CodingCarlos Just found yet another one, seems to work fine to open the direct message option directly :)
https://gfs-madrid.slack.com/app_redirect?channel=UGH2A00SX

**Comment by CodingCarlos** [comment]
Cool! Added!
