### ISSUE TITLE
BR Version Updates (Dec '19)

### ISSUE THREAD

**Issue by musikame** [CampusMadridProjects/directory-frontend#79]
Adjustments shall be applied to both profile pages and registration form/CMS:

- [x] Include Instagram profile link + icon in personal details

- [x] Replace "floor" by "Program" - drop-down options: "Residency", "Launchpad", "GFS Team", "Immersion" and "Exchange"

- [x] Include "Location" field (not all Startups are located in SP)

**Comment by CodingCarlos** [comment]
Ready! All deployed to pro ;)
