### ISSUE TITLE
default picture not showing in last built (TLV)

### ISSUE THREAD

**Issue by ivoriginal** [CampusMadridProjects/directory-frontend#81]
![Screenshot_2020-02-17 Home GFS Directory](https://user-images.githubusercontent.com/10926362/74668295-3a6e9200-51a5-11ea-9fde-4edf73e52f17.png)

**Comment by CodingCarlos** [comment]
This is because not having enabled the / redirection to the directory, but the /preview.

So, when this is done, and it's oficially launched, it will be automatically fixed.

**Comment by ivoriginal** [comment]
Then beware my last commit to new-home-tab ⚠️

**Comment by CodingCarlos** [comment]
No worrys, that is a good fix. It helps a lot to avoid the directory to run only in the root folder ;)
