### ISSUE TITLE
Update CSS for Mobile devices to enable 2/4 visible cards per viewport. 

### ISSUE THREAD

**Issue by musikame** [CampusMadridProjects/directory-frontend#9]
Suggested updates (for review @ivoriginal, @CodingCarlos):

@media (min-width: 600px){

	.card-user-pic{
		calc(40vw - 32px)
	}

}

@media (min-width: 0px){

	.card-user-pic{
		calc(40vw - 32px)
	}

}

.flex.xs12 {
    flex-basis: 50%;
}

.headline {
    font-size: 16px!important;
}

**Comment by CodingCarlos** [comment]
You can also achieve that by using the grid system built in vuetify
framework.

Will provide more details tonight, now I'm quite busy, sorry :S

**Comment by musikame** [comment]
Good call, probably better to manage that way (not familiar with vuetify) to have a similar visual effect,
Gcs Carlos!

**Comment by CodingCarlos** [comment]
Fixed in #18 and waiting to production
